return {
    -- {
    --    "zbirenbaum/copilot.lua",
    --    config = function()
    -- require("copilot").setup({
    --     panel = {
    --         enabled = true,
    --         auto_refresh = false,
    --         keymap = {
    --             jump_prev = "[[",
    --             jump_next = "]]",
    --             accept = "<CR>",
    --             refresh = "gr",
    --         },
    --     },
    --     suggestion = {
    --         enabled = true,
    --         auto_trigger = false,
    --         debounce = 75,
    --     },
    --     filetypes = {
    --         yaml = false,
    --         markdown = false,
    --         help = false,
    --         gitcommit = false,
    --         gitrebase = false,
    --         hgcommit = false,
    --         svn = false,
    --         cvs = false,
    --         ["."] = false,
    --     },
    --     copilot_node_command = 'node', -- Node.js version must be > 16.x
    --     server_opts_overrides = {},
    -- })
    --    end,
    --},
    --{
    --"zbirenbaum/copilot-cmp",
    --      config = function()
    --          require("copilot_cmp").setup()
    --      end,
    --}

    -- {
    -- "tzachar/cmp-tabnine",
    -- build = "./install.sh",
    -- dependencies = "hrsh7th/nvim-cmp"
    -- },
}
